# Generated by Django 2.2.17 on 2022-08-19 05:10

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20220817_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=mdeditor.fields.MDTextField(verbose_name='本文'),
        ),
    ]
