# Generated by Django 2.2.17 on 2022-08-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220819_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='relate_article',
            field=models.ManyToManyField(blank=True, null=True, related_name='_article_relate_article_+', to='polls.Article', verbose_name='関連記事'),
        ),
    ]
